export { StatsCard } from "./stats-card";
export { RecentBookings } from "./recent-bookings";
export { QuickActions } from "./quick-actions";
export { ReservationsTable } from "./reservations-table";
export { AssetsPage } from "./assets-page";
export { SettingsPage } from "./settings-page";
export { PaymentsPage } from "./payments-page";
export { ReportsPage } from "./reports-page";
export { NewBookingPage } from "./new-booking-page";
